# AUTO-GENERATED by scripts/sync-upstream.ts
# Source: upstream/tiktoken @ 6ec8149812275a88a99dfddb54a60b6d98d75bc2

from __future__ import annotations

import pytest

import turbotoken


@pytest.mark.parametrize(
    "text",
    [
        "hello world",
        "token counting for coding agents",
        "line one\\nline two",
        "ASCII punctuation !@#$%^&*()",
        "",
    ],
)
def test_turbotoken_roundtrip_contract(text: str) -> None:
    enc = turbotoken.get_encoding("o200k_base")
    assert enc.decode(enc.encode(text)) == text
