#!/usr/bin/env bun
import { existsSync, lstatSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { commandExists, resolvePath, runCommand, section } from "./_lib";

interface Upstream {
  name: string;
  url: string;
  branch: string;
  optional?: boolean;
  preferSubmodule?: boolean;
}

const upstreams: Upstream[] = [
  {
    name: "tiktoken",
    url: "https://github.com/openai/tiktoken.git",
    branch: "main",
    preferSubmodule: true,
  },
  { name: "rs-bpe", url: "https://github.com/gweidart/rs-bpe.git", branch: "main" },
  { name: "gpt-tokenizer", url: "https://github.com/niieani/gpt-tokenizer.git", branch: "main" },
  { name: "github-bpe", url: "https://github.com/github/bpe.git", branch: "main", optional: true },
  {
    name: "compare-tokenizers",
    url: "https://github.com/transitive-bullshit/compare-tokenizers.git",
    branch: "main",
  },
];

function isGitRepo(path: string): boolean {
  return existsSync(resolve(path, ".git"));
}

function isSubmodule(path: string): boolean {
  const result = runCommand("git", ["submodule", "status", "--", path], { allowFailure: true });
  return result.code === 0;
}

function removeGitKeep(path: string): void {
  const gitKeep = resolve(path, ".gitkeep");
  if (existsSync(gitKeep)) {
    unlinkSync(gitKeep);
  }
}

function cloneReady(path: string): boolean {
  if (!existsSync(path)) {
    return true;
  }
  if (!lstatSync(path).isDirectory()) {
    return false;
  }
  removeGitKeep(path);
  return readdirSync(path).length === 0;
}

function syncRepo(upstream: Upstream): boolean {
  const dir = resolvePath("upstream", upstream.name);

  if (upstream.preferSubmodule) {
    if (!isSubmodule(dir)) {
      section(`Registering ${upstream.name} as submodule`);
      const add = runCommand("git", ["submodule", "add", "--force", upstream.url, dir], {
        allowFailure: true,
      });
      if (add.code !== 0) {
        console.warn(`Failed to register ${upstream.name} as submodule.`);
        return false;
      }
    }

    section(`Updating submodule ${upstream.name}`);
    const update = runCommand(
      "git",
      ["submodule", "update", "--init", "--remote", "--", dir],
      { allowFailure: true },
    );
    if (update.code !== 0) {
      console.warn(`Failed to update submodule ${upstream.name}.`);
      return false;
    }
    return true;
  }

  if (isGitRepo(dir)) {
    section(`Updating ${upstream.name}`);
    runCommand("git", ["-C", dir, "fetch", "origin", upstream.branch]);
    runCommand("git", ["-C", dir, "checkout", upstream.branch], { allowFailure: true });
    const pull = runCommand("git", ["-C", dir, "pull", "--ff-only", "origin", upstream.branch], {
      allowFailure: true,
    });
    if (pull.code !== 0) {
      if (upstream.optional) {
        console.warn(`Could not fast-forward optional upstream ${upstream.name}; skipping.`);
        return true;
      }
      console.warn(`Could not fast-forward ${upstream.name}; leaving repository untouched.`);
      return false;
    }
    return true;
  }

  if (!cloneReady(dir)) {
    console.warn(`Skipping ${upstream.name}: ${dir} is non-empty and not a git repo.`);
    return false;
  }

  section(`Cloning ${upstream.name}`);
  mkdirSync(dirname(dir), { recursive: true });
  const clone = runCommand(
    "git",
    ["clone", "--depth", "1", "--branch", upstream.branch, upstream.url, dir],
    { allowFailure: true },
  );

  if (clone.code !== 0) {
    if (upstream.optional) {
      console.warn(`Failed to clone optional upstream ${upstream.name}; skipping.`);
      return true;
    }
    console.warn(`Failed to clone ${upstream.name}`);
    return false;
  }

  return true;
}

function adaptTiktokenSmoke(syncSucceeded: boolean): void {
  if (!syncSucceeded) {
    return;
  }

  const upstreamRoot = resolvePath("upstream", "tiktoken");
  if (!existsSync(upstreamRoot)) {
    return;
  }

  const hasEncodingTest = existsSync(resolve(upstreamRoot, "tests", "test_encoding.py"));
  if (!hasEncodingTest) {
    return;
  }

  const commit = runCommand("git", ["-C", upstreamRoot, "rev-parse", "HEAD"], {
    allowFailure: true,
  }).stdout.trim();

  const outDir = resolvePath("python", "tests", "upstream");
  const outPath = resolve(outDir, "test_tiktoken_sync.py");
  mkdirSync(outDir, { recursive: true });

  const contents = `# AUTO-GENERATED by scripts/sync-upstream.ts\n# Source: upstream/tiktoken @ ${commit || "unknown"}\n\nfrom __future__ import annotations\n\nimport pytest\n\nimport turbotoken\n\n\n@pytest.mark.parametrize(\n    \"text\",\n    [\n        \"hello world\",\n        \"token counting for coding agents\",\n        \"line one\\\\nline two\",\n        \"ASCII punctuation !@#$%^&*()\",\n        \"\",\n    ],\n)\ndef test_turbotoken_roundtrip_contract(text: str) -> None:\n    enc = turbotoken.get_encoding(\"o200k_base\")\n    assert enc.decode(enc.encode(text)) == text\n`;
  writeFileSync(outPath, contents, "utf8");
}

if (!commandExists("git")) {
  console.error("git is required to sync upstream repositories");
  process.exit(1);
}

let tiktokenSynced = false;
let failures = 0;

for (const upstream of upstreams) {
  const ok = syncRepo(upstream);
  if (upstream.name === "tiktoken") {
    tiktokenSynced = ok;
  }
  if (!ok) {
    failures += 1;
  }
}

adaptTiktokenSmoke(tiktokenSynced);

if (failures > 0) {
  console.warn(`sync-upstream completed with ${failures} warning(s)`);
}
